name: prebuild
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
permissions:
  contents: read

jobs:
  prebuid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # it is required fot the changelog to work correctly
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: |
          make build && make clean
